### PR TITLE
Use '/proc/meminfo' as source for memory information.

### PR DESCRIPTION
**Pull request by eidottermihi**
This should work on all distributions (no need for free, top, or vmstat) and also can provide "available memory".
Should therefore work on Arch Linux too #106

### CODE REVIEW

**Comment by eidottermihi** [comment]
@indywidualny Could you check if 
```
cat /proc/cpuinfo | tr -s " "
```
results in something similiar to this on Arch Linux:
```
MemTotal: 949328 kB
MemFree: 49512 kB
MemAvailable: 884628 kB
Buffers: 437356 kB
Cached: 411156 kB
SwapCached: 0 kB
Active: 430840 kB
Inactive: 431320 kB
Active(anon): 7116 kB
Inactive(anon): 7956 kB
Active(file): 423724 kB
Inactive(file): 423364 kB
Unevictable: 0 kB
Mlocked: 0 kB
SwapTotal: 102396 kB
SwapFree: 102392 kB
Dirty: 36 kB
Writeback: 0 kB
AnonPages: 13552 kB
Mapped: 9852 kB
Shmem: 1424 kB
Slab: 27628 kB
SReclaimable: 17016 kB
SUnreclaim: 10612 kB
KernelStack: 736 kB
PageTables: 672 kB
NFS_Unstable: 0 kB
Bounce: 0 kB
WritebackTmp: 0 kB
CommitLimit: 577060 kB
Committed_AS: 50992 kB
VmallocTotal: 1105920 kB
VmallocUsed: 1116 kB
VmallocChunk: 886668 kB
```

**Comment by indywidualny** [comment]
Unfortunately the output is completely different. 
```
pizero $ ~  cat /proc/cpuinfo | tr -s " "
catprocessor    : 0
model name      : ARMv6-compatible processor rev 7 (v6l)
BogoMIPS        : 2.00
Features        : half thumb fastmult vfp edsp java tls
CPU implementer : 0x41
CPU architecture: 7
CPU variant     : 0x0
CPU part        : 0xb76
CPU revision    : 7
 
Hardware        : BCM2708
Revision        : 900092
Serial          : 00000000e97d881a
pizero $ ~
```

**Comment by eidottermihi** [comment]
Oh my bad, I mean
```
cat /proc/meminfo | tr -s " "
```
:grin:

**Comment by indywidualny** [comment]
Now it's ok :)
```
pizero $ ~  cat /proc/meminfo | tr -s " "
MemTotal: 442788 kB
MemFree: 23064 kB
MemAvailable: 403180 kB
Buffers: 37692 kB
Cached: 325560 kB
SwapCached: 0 kB
Active: 159036 kB
Inactive: 216260 kB
Active(anon): 12280 kB
Inactive(anon): 120 kB
Active(file): 146756 kB
Inactive(file): 216140 kB
Unevictable: 0 kB
Mlocked: 0 kB
SwapTotal: 0 kB
...
```

**Pull request merged**
